FROM golang:1.22.2
WORKDIR /app

# 依存キャッシュ用ステージ
# go.modとgo.sumが存在しない場合のための対応
COPY go.* ./
RUN if [ -f go.mod ]; then \
        go mod download; \
    else \
        go mod init cow-templates && \
        go mod tidy; \
    fi

# 残りのアプリコードをコピー
COPY . .

# .git や .github が混入していたら削除
RUN rm -rf .git .github

# Air をインストール
RUN go install github.com/air-verse/air@v1.52.3

EXPOSE 8000
CMD ["air"]
